[variables]
NODE_ENV = "production"

[phases.setup]
nixPkgs = ["python3", "python3Packages.pip", "nodejs-18_x", "npm-9_x"]

[phases.install]
cmd = "npm ci"

[phases.build]
cmds = ["pip3 install -r requirements.txt", "npm run build"]

[start]
cmd = "npm run start" 