[variables]
NODE_ENV = "production"

[phases.setup]
nixPkgs = ["python3", "python3Packages.pip", "python3Packages.virtualenv", "nodejs-18_x", "npm-9_x"]

[phases.install]
cmd = "npm ci"

[phases.build]
cmds = [
  "chmod +x run_transcript.sh",
  "chmod +x transcript_extractor.py",
  "python3 -m venv transcript_venv",
  "source transcript_venv/bin/activate && pip install --upgrade pip",
  "source transcript_venv/bin/activate && pip install -r requirements.txt",
  "npm run build"
]

[start]
cmd = "npm run start" 