[variables]
NODE_ENV = "production"

[phases.setup]
nixPkgs = ["python3", "python3Packages.pip", "python3Packages.virtualenv", "nodejs-18_x", "npm-9_x"]

[phases.install]
cmd = "npm ci"

[phases.build]
cmds = [
  "chmod +x run_transcript.sh",
  "chmod +x transcript_extractor.py", 
  "chmod +x check_environment.sh",
  "chmod +x verify_api_migration.py",
  "python3 -m venv transcript_venv --system-site-packages",
  "transcript_venv/bin/pip install --upgrade pip",
  "transcript_venv/bin/pip install youtube-transcript-api==1.2.1",
  "transcript_venv/bin/pip install yt-dlp",
  "./check_environment.sh",
  "echo '⚠️ Skipping API verification during build - will test at runtime with proxy'",
  "npm run build"
]

[start]
cmd = "npm run start" 