[variables]
NODE_ENV = "production"

[phases.setup]
nixPkgs = ["nodejs-18_x", "npm-9_x", "python3", "python3Packages.pip"]

[phases.install]
cmd = "npm ci && pip3 install -r requirements.txt"

[phases.build] 
cmd = "npm run build"

[start]
cmd = "npm run start" 